### ISSUE TITLE
大佬你好，有个问题请教

### ISSUE THREAD

**Issue by Herclues** [lemoeo/AX6S#3]
由于需要使用IPTV，因此我修改了/lib/netifd/proto/dhcp.sh 和 /etc/config/network ,现在都已经配置完成，可以正常使用，但是路由器一旦重启 ，所有的修改都会丢失，该如何固化修改呢，我仿照您配置了一个firewall ，但是脚本并没有如期执行
`mount --bind /data/uci/dhcp.sh /lib/netifd/proto/dhcp.sh

sleep 20

uci delete network.vlan3.ports

uci set network.vlan6=switch_vlan
uci set network.vlan6.device='switch0'
uci set network.vlan6.vlan='6'
uci set network.vlan6.vid='6'
uci set network.vlan6.ports='3 5t'

uci set network.eth1_6=interface
uci set network.eth1_6.ifname='eth1.6'

uci set network.iptv=interface
uci set network.iptv.proto='dhcp'
uci set network.iptv.hostname='F0000441001338300000585FF6E48DC3'
uci set network.iptv.sendopts='0x3c:xxxxxxxx'
uci set network.iptv.delegate='0'
uci set network.iptv.metric='20'
uci set network.iptv.macaddr=''58:5f:f6:e4:8d:c3''
uci set network.iptv.ifname='eth1.6'

uci commit

/etc/init.d/network reload

/data/udpxy -p 4022 -m eth1.6`

希望获得您的指点，谢谢

**Comment by lemoeo** [comment]
参照以下代码设置启动后自动运行的脚本
```
# Add script to system autostart
uci set firewall.auto_ssh=include
uci set firewall.auto_ssh.type='script'
uci set firewall.auto_ssh.path="${auto_ssh_dir}/auto_ssh.sh"
uci set firewall.auto_ssh.enabled='1'
uci commit firewall
```
